name: Build and Publish NuGet

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  NUGET_URL: https://int.nugettest.org

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: | 
        dotnet build --configuration Release 
        dotnet pack --configuration Release --output .
 
    - name: Publish
      run: |
        dotnet nuget push NugetHelloSCITT\TravisJCo.HelloSCITT.0.1.0.nupkg --api-key ${{ secrets.NUGET_API_KEY_INT }} --source ${{ env.NUGET_URL }}
