name: Build and Publish NuGet

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  NUGET_URL: https://int.nugettest.org

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: | 
        dotnet build --configuration Release --output buildOutput 
        
    - name: Generate SBOM
      run: |
        curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        chmod +x $RUNNER_TEMP/sbom-tool
        $RUNNER_TEMP/sbom-tool generate -b ./buildOutput -bc . -pn NugetHelloSCITT -pv 1.0.0 -ps TravisJCo -nsb https://sbom.travisjco.com

    - name: NuGet Pack
      run: | 
        dotnet pack --no-build --output . /p:OutputPath=buildOutput
 
    - name: NuGet Publish
      run: |
        dotnet nuget push TravisJCo.HelloSCITT.0.1.0.nupkg --api-key ${{ secrets.GH_NUGET_PAT }} --source "https://nuget.pkg.github.com/travisjmsft/index.json" --skip-duplicate
